name: CI-SFTP
on:
  push:
    branches: [ Development ]

jobs:
    deploy-via-sftp:
      runs-on: ubuntu-latest
      steps:
        uses: actions/checkout@v2
        - name: SFTP Deploy
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
            username: ${{ secrets.FTP_USERNAME }}
            server: ${{ secrets.FTP_SERVER }}
            port: ${{ secrets.FTP_PORT }}
            local_path: './static/*'
            remote_path: '/wp-content/themes/'
            sftp_only: true
            password: ${{ secrets.FTP_PASSWORD }}

